/* Generated by Kodofy by Dark CSS */
document.addEventListener('DOMContentLoaded', () => {

  const menuBtn = document.getElementById('mobile-menu-btn');
  const drawer = document.getElementById('mobile-drawer');
  const header = document.getElementById('site-header');
  if(menuBtn && drawer) {
    menuBtn.addEventListener('click', () => {
      drawer.classList.toggle('open');
      if(header) header.classList.toggle('mobile-menu-open');
      if (drawer.classList.contains('open')) document.body.classList.add('overflow-hidden');
      else document.body.classList.remove('overflow-hidden');
      menuBtn.innerHTML = drawer.classList.contains('open') ? '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M18 6 6 18"/><path d="m6 6 12 12"/></svg>' : '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="4" x2="20" y1="12" y2="12"/><line x1="4" x2="20" y1="6" y2="6"/><line x1="4" x2="20" y1="18" y2="18"/></svg>';
    });

    drawer.querySelectorAll('a').forEach(link => {
      link.addEventListener('click', () => {
        drawer.classList.remove('open');
        if(header) header.classList.remove('mobile-menu-open');
        document.body.classList.remove('overflow-hidden');
        menuBtn.innerHTML = '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="4" x2="20" y1="12" y2="12"/><line x1="4" x2="20" y1="6" y2="6"/><line x1="4" x2="20" y1="18" y2="18"/></svg>';
      });
    });

    window.addEventListener('resize', () => {
      if (window.innerWidth > 1024 && drawer.classList.contains('open')) {
        drawer.classList.remove('open');
        if(header) header.classList.remove('mobile-menu-open');
        document.body.classList.remove('overflow-hidden');
        menuBtn.innerHTML = '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="4" x2="20" y1="12" y2="12"/><line x1="4" x2="20" y1="6" y2="6"/><line x1="4" x2="20" y1="18" y2="18"/></svg>';
      }
    });
  }

  const themeBtns = document.querySelectorAll('.theme-toggle-btn');
  const moonIcon = `<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z"/></svg>`;
  const sunIcon = `<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="4"/><path d="M12 2v2"/><path d="M12 20v2"/><path d="m4.93 4.93 1.41 1.41"/><path d="m17.66 17.66 1.41 1.41"/><path d="M2 12h2"/><path d="M20 12h2"/><path d="m6.34 17.66-1.41 1.41"/><path d="m19.07 4.93-1.41 1.41"/></svg>`;

  const savedTheme = localStorage.getItem('theme') || 'light';
  document.body.setAttribute('data-theme', savedTheme);
  themeBtns.forEach(btn => btn.innerHTML = savedTheme === 'dark' ? sunIcon : moonIcon);

  themeBtns.forEach(btn => {
    btn.addEventListener('click', () => {
      const body = document.body;
      const currentTheme = body.getAttribute('data-theme');
      const newTheme = currentTheme === 'dark' ? 'light' : 'dark';
      body.setAttribute('data-theme', newTheme);
      localStorage.setItem('theme', newTheme);
      themeBtns.forEach(b => b.innerHTML = newTheme === 'dark' ? sunIcon : moonIcon);
    });
  });

  
  const typewriters = document.querySelectorAll('.typewriter-span');
  typewriters.forEach(span => {
    const raw = span.dataset.texts;
    if(!raw) return;
    try {
      const texts = JSON.parse(raw);
      let tIdx = 0, cIdx = 0, isDel = false;
      function type() {
        const full = texts[tIdx];
        if(isDel) { span.textContent = full.substring(0, cIdx-1); cIdx--; }
        else { span.textContent = full.substring(0, cIdx+1); cIdx++; }
        
        let speed = isDel ? 50 : 100;
        if(!isDel && cIdx === full.length) { isDel = true; speed = 2000; }
        else if(isDel && cIdx === 0) { isDel = false; tIdx = (tIdx+1)%texts.length; speed = 500; }
        setTimeout(type, speed);
      }
      type();
    } catch(e){}
  });

  

  
  const contactForm = document.querySelector('.contact-form');
  if(contactForm) {
    contactForm.addEventListener('submit', (e) => {
      e.preventDefault();
      alert('Message sent! We will get back to you soon.');
      contactForm.reset();
    });
  }

});
